# Generated by Django 4.2.25 on 2026-01-20 03:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDefinition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('agent_type', models.CharField(choices=[('local', 'Local'), ('premium', 'Premium')], max_length=20)),
                ('category', models.CharField(choices=[('drafting', 'Drafting'), ('review', 'Review'), ('analysis', 'Analysis'), ('perfecting', 'Perfecting'), ('response', 'Response'), ('strategy', 'Strategy'), ('orchestrator', 'Orchestrator'), ('custom', 'Custom')], default='custom', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('current_version', models.CharField(default='v1', max_length=20)),
                ('allowed_modes', models.JSONField(blank=True, default=list, help_text="List of allowed modes: ['chat', 'edit', 'ask', 'agent']")),
                ('color', models.CharField(default='#3B82F6', help_text='Hex color for UI display', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=100)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Agent-specific configuration')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_agent_definition',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PatentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('invention_title', models.CharField(blank=True, max_length=500)),
                ('technical_field', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('drafting', 'Drafting'), ('review', 'Under Review'), ('perfecting', 'Perfecting'), ('filed', 'Filed'), ('examining', 'Under Examination'), ('granted', 'Granted'), ('abandoned', 'Abandoned')], default='drafting', max_length=50)),
                ('invention_disclosure', models.JSONField(blank=True, default=dict)),
                ('claims', models.JSONField(blank=True, default=list)),
                ('specification', models.JSONField(blank=True, default=dict)),
                ('drawings_description', models.TextField(blank=True)),
                ('prior_art_references', models.JSONField(blank=True, default=list)),
                ('office_actions', models.JSONField(blank=True, default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('premium_session_ref', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_session',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('mock_examiner_used', models.IntegerField(default=0)),
                ('mock_examiner_limit', models.IntegerField(default=3)),
                ('office_action_used', models.IntegerField(default=0)),
                ('office_action_limit', models.IntegerField(default=0)),
                ('claim_strategy_used', models.IntegerField(default=0)),
                ('claim_strategy_limit', models.IntegerField(default=0)),
                ('specification_perfection_used', models.IntegerField(default=0)),
                ('specification_perfection_limit', models.IntegerField(default=0)),
                ('reset_date', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patent_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_subscription_quota',
            },
        ),
        migrations.CreateModel(
            name='PriorArtReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('source', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('summary', models.TextField(blank=True)),
                ('claims_affected', models.JSONField(default=list)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prior_art', to='patent.patentsession')),
            ],
            options={
                'db_table': 'patent_prior_art',
            },
        ),
        migrations.CreateModel(
            name='PremiumAgentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('mock_examiner', 'Mock Examiner'), ('office_action_response', 'Office Action Response'), ('claim_strategy', 'Claim Strategy'), ('specification_perfection', 'Specification Perfection')], max_length=50)),
                ('request_data', models.JSONField(default=dict)),
                ('response_data', models.JSONField(default=dict)),
                ('tokens_used', models.IntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_usage', to='patent.patentsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_agent_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patent_premium_agent_usage',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_type', models.CharField(choices=[('rejection_101', '101 Rejection'), ('rejection_102', '102 Rejection'), ('rejection_103', '103 Rejection'), ('objection', 'Objection'), ('requirement', 'Requirement'), ('allowance', 'Allowance')], max_length=50)),
                ('content', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('response_draft', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('drafting', 'Drafting'), ('filed', 'Filed'), ('responded', 'Responded')], default='pending', max_length=50)),
                ('examiner_notes', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_actions_history', to='patent.patentsession')),
            ],
            options={
                'db_table': 'patent_office_action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.IntegerField()),
                ('claim_type', models.CharField(choices=[('independent', 'Independent'), ('dependent', 'Dependent')], max_length=20)),
                ('depends_on', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('perfected', 'Perfected'), ('final', 'Final')], default='draft', max_length=50)),
                ('amendments', models.JSONField(blank=True, default=list)),
                ('examiner_comments', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_drafts', to='patent.patentsession')),
            ],
            options={
                'db_table': 'patent_claim_draft',
                'ordering': ['claim_number'],
            },
        ),
        migrations.CreateModel(
            name='AgentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=20)),
                ('system_prompt', models.TextField()),
                ('changelog', models.TextField(blank=True)),
                ('config_snapshot', models.JSONField(default=dict)),
                ('is_active_version', models.BooleanField(default=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='patent.agentdefinition')),
            ],
            options={
                'db_table': 'patent_agent_version',
                'ordering': ['-created_at'],
            },
        ),
    ]
