# Generated by Django 4.2.25 on 2026-01-20 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_drafter_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_drafter_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_illustrator_limit',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_illustrator_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_interrogator_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_interrogator_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_searcher_limit',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='subscriptionquota',
            name='patent_searcher_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premiumagentusage',
            name='agent_type',
            field=models.CharField(choices=[('mock_examiner', 'Mock Examiner'), ('office_action_response', 'Office Action Response'), ('claim_strategy', 'Claim Strategy'), ('specification_perfection', 'Specification Perfection'), ('patent_searcher', 'Patent Searcher'), ('patent_drafter', 'Patent Drafter'), ('patent_interrogator', 'Patent Interrogator'), ('patent_illustrator', 'Patent Illustrator')], max_length=50),
        ),
    ]
