# Generated by Django 4.2.25 on 2026-01-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patent', '0002_subscriptionquota_patent_drafter_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionquota',
            name='patent_illustrator_limit',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscriptionquota',
            name='patent_searcher_limit',
            field=models.IntegerField(default=3),
        ),
    ]
