name: OpenPatent
options:
  bundleIdPrefix: ai.openpatent
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic

targets:
  OpenPatent:
    type: application
    platform: iOS
    sources:
      - path: OpenPatent
        excludes:
          - "**/*.entitlements"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openpatent.OpenPatent
        INFOPLIST_FILE: OpenPatent/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: OpenPatent/Resources/OpenPatent.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        GENERATE_INFOPLIST_FILE: false
        SWIFT_EMIT_LOC_STRINGS: YES
        ENABLE_PREVIEWS: YES
    entitlements:
      path: OpenPatent/Resources/OpenPatent.entitlements
      properties:
        keychain-access-groups:
          - $(AppIdentifierPrefix)ai.openpatent.OpenPatent

  OpenPatentTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: OpenPatentTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openpatent.OpenPatentTests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: OpenPatent

  OpenPatentUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: OpenPatentUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ai.openpatent.OpenPatentUITests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: OpenPatent
